"""Add project management support

Revision ID: 7e0ea2c13577
Revises: 
Create Date: 2026-01-28 20:57:50.910831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0ea2c13577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Create projects table if it doesn't exist
    # (it might already exist from db initialization)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'projects' not in inspector.get_table_names():
        op.create_table('projects',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name_ar', sa.String(200), nullable=False),
            sa.Column('name_en', sa.String(200), nullable=True),
            sa.Column('is_active', sa.Boolean(), default=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    # Step 2: Insert default project for existing data
    op.execute("""
        INSERT OR IGNORE INTO projects (id, name_ar, name_en, is_active, created_at, updated_at)
        VALUES (1, 'المشروع الرئيسي', 'Main Project', 1, datetime('now'), datetime('now'))
    """)

    # Step 3: Add project_id columns as NULLABLE first
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('income_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    # Step 4: Migrate existing data to default project (id=1)
    op.execute("UPDATE accounts SET project_id = 1 WHERE project_id IS NULL")
    op.execute("UPDATE employees SET project_id = 1 WHERE project_id IS NULL")
    op.execute("UPDATE debts SET project_id = 1 WHERE project_id IS NULL")

    # For transactions, set project_id based on their account's project
    op.execute("""
        UPDATE income_transactions
        SET project_id = (SELECT project_id FROM accounts WHERE accounts.id = income_transactions.account_id)
        WHERE project_id IS NULL
    """)

    op.execute("""
        UPDATE expense_transactions
        SET project_id = (SELECT project_id FROM accounts WHERE accounts.id = expense_transactions.account_id)
        WHERE project_id IS NULL
    """)

    # Step 5: Make project_id NOT NULL and add foreign keys
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_foreign_key('fk_accounts_project', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_foreign_key('fk_employees_project', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_foreign_key('fk_debts_project', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('income_transactions', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_foreign_key('fk_income_transactions_project', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_foreign_key('fk_expense_transactions_project', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
